<?php
/**
 * 
 * @category    design
 * @package     default_modern
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 */
?>
<?php 
//$x = $this->helper('solr')->searchRes('cobra', 'KTS_DEV');
//var_dump($x);
?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
<!-- form id="search_mini_form" action="/solr" method="get"-->
    <div class="form-search">
        <label for="search">Search</label>
        <input id="search" type="text" name="qRec" value="Search KensToolSupply.com" class="input-text" />
        <button type="submit" title="Go" class="button"><span>Go</span></button>
        <!-- div id="search_autocomplete" class="search-autocomplete"></div -->
        <script type="text/javascript">
        //<![CDATA[
        jQuery(document).ready(function ($){ 
            if($('#search')==null){$('#search').val('Search KensToolSupply.com');}
			var baseUrl='<?php echo $this->getBaseUrl(); ?>';
            $('#search').autocomplete({  source: function(request,response){$.getJSON(baseUrl+'solr/index/index',{sug:request.term},response);}	});
			var srchTxt="Search KensToolSupply.com";
			$('#search').val("Search KensToolSupply.com");
			//$('#search').val("<?php echo $this->getBaseUrl(); ?>");
			$('#search').focus(  function(){  if($('#search').val(srchTxt)){  $('#search').val("");  }  });
			$('#search').blur(  function(){  if(!$('#search').val()){  $('#search').val(srchTxt);  }  });
        });
        //]]>
        </script>
    </div>
</form>